name: Push notification

on: [push]

jobs:
    run-shell-command:
      runs-on: ubuntu-latest
      steps:
        - name: echo a string
          run: eccho "A push has done"
        - name: multiline script
          run: |
            node -v
            npm -v
